AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates DynamoDB table to store invoices data

Parameters:
  TableName:
    Type: String
    Description: Invoices table name

  ProjectName:
    Description: Project or repository name used to identify created AWS resources
    Type: String

Resources: 
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName
